### ISSUE TITLE
Backward compatible capo and octave/transpose options

### ISSUE THREAD

**Issue by Gubbledenut** [bazmonk/digigurdy-baz#35] opened 2022-03-10 10:10 UTC
John did have key combos attached as well as he assigned the capo and octave on pins 21,22,23 
This is required for older digi gurdies without the three buttons. Need to ensure the key combo is also in your code![image](https://user-images.githubusercontent.com/77911907/157639805-43040973-9bb8-476a-93ae-2251cfc2ec2d.jpeg)

**Comment by bazmonk** [comment] 2022-03-10 17:12
Thanks for showing me the alternate keyings.  This will be a 1.0 thing.

**Comment by bazmonk** [comment] 2022-03-15 01:38
Duplicate of https://github.com/bazmonk/digigurdy-baz/issues/37, or vice versa... either way, done :-)

**Closed by bazmonk** 2022-03-15 01:38 UTC
Labels: enhancement
